import { readFileSync, writeFileSync } from "node:fs";
import { toZhCn as convert } from "./zh-cn.mjs";   // the SAME module render-profile.mjs uses for README.zh-CN.md (opencc-js twp→cn + PROTECTED official names)
const root = new URL("../", import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root), "utf8"));
const ZH_KEYS = new Set(["zh", "descZh"]);
// Convert every string stored under a zh/descZh key, anywhere in the object; copy everything else as-is.
function walk(value, key) {
  if (typeof value === "string") return ZH_KEYS.has(key) ? convert(value) : value;
  if (Array.isArray(value)) return value.map((v) => walk(v, key));
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, walk(v, k)]));
  return value;
}
const ui = read("src/data/ui.json");          // { en: {...}, "zh-Hant": {...} }
const out = {
  note: "Generated by scripts/build-zh-hans.mjs from zh-Hant sources with opencc-js (tw→cn). Do not edit.",
  ui: walk(ui["zh-Hant"], "zh"),              // whole zh-Hant UI object converted
  catalog: walk(read("src/data/projects.json"), ""),
  caseStudies: walk(read("src/data/case-studies.json"), ""),
};
const text = JSON.stringify(out, null, 2) + "\n";
const target = new URL("src/data/zh-hans.generated.json", root);
if (process.argv.includes("--check")) {
  let current = ""; try { current = readFileSync(target, "utf8"); } catch {}
  if (current !== text) { console.error("zh-Hans copy is stale: run npm run locale"); process.exit(1); }
  console.log("zh-Hans copy is current.");
} else { writeFileSync(target, text); console.log("Wrote src/data/zh-hans.generated.json"); }
